# A simple name for your workflow
name: Build Windows Executable

# This tells GitHub to run the workflow every time you 'push' code
on: [push]

jobs:
  build-windows:
    # This job will run on a virtual Windows machine provided by GitHub
    runs-on: windows-latest

    steps:
      # 1. Checks out a copy of your repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Sets up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can change the Python version if needed

      # 3. Installs your dependencies (in this case, just PyInstaller)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # 4. Runs the PyInstaller command to build your executable
      - name: Build with PyInstaller
        run: pyinstaller --name "RoomScenarioGame" --onefile --clean run_game.py

      # 5. Uploads the final .exe file so you can download it
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoomScenarioGame-Windows # The name of the downloadable file
          path: dist/RoomScenarioGame.exe # The path to the file to upload